# -*- coding: utf-8 -*-
"""first_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gKfhVI6rA_g_cw8NiMcxtlI-0dEJRgUE
"""

from langchain_core.messages import HumanMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, START, END
from typing import List, TypedDict

api_key = "some_api_key"

llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",
    temperature=1,
    google_api_key= api_key
)

class AgentState(TypedDict):
  messages: List[HumanMessage]

def process_node(state: AgentState) -> AgentState:
  response = llm.invoke(state["messages"])
  print(f"\nAI:", response.content)
  return state

builder = StateGraph(AgentState)

builder.add_node("process_node", process_node)
builder.add_edge(START, "process_node")
builder.add_edge("process_node", END)

app = builder.compile()

userinput = input("Enter: ")
while userinput != "exit":
  app.invoke({
    "messages": [HumanMessage(content=userinput)]
  })
  userinput = input("Enter: ")