# -*- coding: utf-8 -*-
"""lg_exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qVtqKKzFjU03-52bfRCyrA3ageWrYobc
"""

pip install -U langgraph typing

from typing import Dict, TypedDict
from langgraph.graph import StateGraph

class AgentState(TypedDict):
  message: str
  name: str
  location: str
  hobbies: list[str]
  full_description: str

def person_node(state: AgentState) -> AgentState:
  """This node show a person detalis like his/her name message and hobbies"""
  hobbies_str = ", ".join(state["hobbies"])
  state["full_description"] = f"Hi, i am {state['name']} my hobbies are {hobbies_str} and my message is {state['message']} for the people living in {state['location']}"
  return state

graph = StateGraph(AgentState)

graph.add_node("person", person_node)
graph.set_entry_point("person")
graph.set_finish_point("person")

app = graph.compile()

from IPython.display import display, Image
display(Image(app.get_graph().draw_mermaid_png()))

result = app.invoke({
    "name": "Manzoor",
    "location": "Agrikalan",
    "hobbies": ["playing", "chess", "cricket"],  # actual list, not string
    "message": "Excited to connect!"  # include initial message
})

result["full_description"]