# -*- coding: utf-8 -*-
"""multiplenodesLG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19XQGkG9xKBI4JY5kmxj_n6GUrW4Ok28g
"""

from typing import TypedDict
from langgraph.graph import StateGraph

class AgentState(TypedDict):
    name: str
    age : str
    adress: str
    final : str

def first_node(state: AgentState) -> AgentState:
  """First Node that will add name to the state"""
  state["final"] = f"Hello {state['name']}"
  return state

def second_node(state: AgentState) -> AgentState:
  """Second Node that will add age to the state"""
  state["final"] =  f"{state['final']} you are {state['age']} years old"
  return state

def third_node(state: AgentState) -> AgentState:
  """Third Node that will add age to the state"""
  state["final"] =  f" {state['final']} and you are living in {state['adress']} and you are awesome"
  return state

graph = StateGraph(AgentState)
graph.add_node("First Node", first_node)
graph.add_node("Second Node", second_node)
graph.add_node("Third Node", third_node)

graph.set_entry_point("First Node")
graph.add_edge("First Node", "Second Node")
graph.add_edge("Second Node", "Third Node")
graph.set_finish_point("Third Node")

app = graph.compile()

from IPython.display import Image , display
display(Image(app.get_graph().draw_mermaid_png()))

reslut = app.invoke({
    "name": "John",
    "age": "30",
    "adress": "New York"
})

reslut['final']