# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pEjK1lKUH6zLkXDxAi3bo-8o7AXILjIh
"""


from typing import TypedDict, List
from langgraph.graph import StateGraph
import operator as op

class AgentState(TypedDict):
    numbers: List[int]
    mathoperator: str
    name: str
    result : str

def perform_math(operator: str, numbers:List[int]):
  if operator == '+':
    return sum(numbers)
  elif operator == '-':
    # For subtraction, subtract subsequent numbers from the first
    result = numbers[0]
    for num in numbers[1:]:
      result = op.sub(result, num)
    return result
  elif operator == '*':
    # For multiplication, multiply all numbers
    result = 1
    for num in numbers:
      result = op.mul(result, num)
    return result
  elif operator == '/':
    # For division, divide the first number by subsequent numbers
    if 0 in numbers[1:]:
        raise ValueError("Division by zero is not allowed.")
    result = numbers[0]
    for num in numbers[1:]:
      result = op.truediv(result, num)
    return result

def simple_calc(state: AgentState) -> AgentState:
  """this node will receive the list of ints and make any math opration on that list"""
  answer =  perform_math(state['mathoperator'],state['numbers'])
  state['result'] = f"Hey, {state['name']} your result is {answer}"
  return state

graph = StateGraph(AgentState)

graph.add_node("calc",simple_calc)
graph.set_entry_point('calc')
graph.set_finish_point('calc')

app = graph.compile()

from IPython.display import display, Image
display(Image(app.get_graph().draw_mermaid_png()))

output = app.invoke({
    "name":"Manzoor",
    "numbers":[18, 2,3,5],
    "mathoperator":"-"
})

output['result']